# Generated by Django 5.2.4 on 2025-08-27 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
