# Generated by Django 5.2.4 on 2025-08-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_or_meter_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='transaction',
            name='data_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.wallet'),
            preserve_default=False,
        ),
    ]
